"""
Hand-written sentiment sentences.

Every sentence below was composed directly (not generated by combining
templates + subject lists, and not scraped from Twitter/news/movie-critic
corpora). The goal is to cover the register that was missing from the
other data sources: short, plain, everyday declarative English - the kind
of sentence a person actually types when testing a sentiment model
("I love this product.", "It is raining outside today.").

Both SHORT sentences (roughly 3-8 words - good for exercising an RNN/LSTM
on brief inputs) and LONGER sentences (roughly 12-25 words - good for
exercising the network's ability to carry sentiment across a longer
sequence) are included for every class, in roughly equal proportion.
"""

POSITIVE_SHORT = [
    "I love this product.",
    "This is amazing!",
    "Great job, well done.",
    "I'm so happy right now.",
    "What a beautiful morning.",
    "This phone works perfectly.",
    "I really enjoyed that.",
    "You did a fantastic job.",
    "This is exactly what I wanted.",
    "I'm thrilled with the results.",
    "The coffee here is fantastic.",
    "That was a wonderful surprise.",
    "This app is so useful.",
    "I couldn't be happier.",
    "The food was delicious.",
    "This laptop is excellent.",
    "I'm very impressed.",
    "That made my whole day.",
    "This is a great deal.",
    "I feel really good about this.",
    "The service here is excellent.",
    "This book is fantastic.",
    "I highly recommend it.",
    "That was a great match.",
    "This place is wonderful.",
    "I'm proud of this work.",
    "The movie was amazing.",
    "This is such good news.",
    "I really like this design.",
    "That was very kind of you.",
    "This car drives beautifully.",
    "The view is absolutely stunning.",
    "I'm grateful for your help.",
    "This is a lovely house.",
    "The team did a great job.",
    "I love how this turned out.",
    "This was money well spent.",
    "The garden looks beautiful.",
    "I'm delighted with my purchase.",
    "This is a huge relief.",
]

POSITIVE_LONG = [
    "I absolutely love this product; it works perfectly every single time I use it.",
    "The customer service team was friendly, patient, and genuinely helpful throughout the whole process.",
    "This restaurant serves delicious food every time we visit, and the staff are always welcoming.",
    "I am extremely happy with my purchase and would gladly buy from this company again.",
    "The hotel room was clean, spacious, and comfortable, exactly what we needed after a long flight.",
    "Everyone on the team worked together brilliantly, and we finished the entire project ahead of schedule.",
    "My new laptop is fast, reliable, and has made my daily work so much easier to manage.",
    "The concert last night was absolutely incredible, with an energy that kept the whole crowd smiling.",
    "This software update fixed every bug we reported and now runs more smoothly than ever before.",
    "The doctor was patient, explained everything clearly, and made sure all of my questions were answered.",
    "I felt genuinely welcomed the moment I walked through the door, and that warmth continued the entire visit.",
    "The view from the mountain top was breathtaking, easily the best part of our entire trip.",
    "This is a wonderful neighborhood to raise a family, with friendly neighbors and excellent schools nearby.",
    "The instructions were clear and easy to follow, so the whole setup only took a few minutes.",
    "I appreciate how quickly the support team resolved my issue without making me repeat myself twice.",
    "Her cooking always brings the whole family together, and everyone leaves the table completely satisfied.",
    "The new employee has been a great addition to the team, bringing energy and fresh ideas every day.",
    "I'm thrilled with how the kitchen renovation turned out; it looks better than I ever imagined.",
    "This software saved me hours of work every week, and the interface is intuitive and pleasant to use.",
    "The sunrise this morning over the lake was absolutely stunning and made the early wake-up worth it.",
]

NEGATIVE_SHORT = [
    "I hate this product.",
    "This is terrible.",
    "What a disappointing experience.",
    "I regret buying this item.",
    "This phone is very slow.",
    "That was a complete waste of time.",
    "I'm really upset about this.",
    "This is not good at all.",
    "The food tasted awful.",
    "I'm very disappointed.",
    "This is such a letdown.",
    "That was a bad decision.",
    "This app keeps crashing.",
    "I can't stand this noise.",
    "The service was rude.",
    "This is a huge mistake.",
    "I feel really frustrated.",
    "That movie was terrible.",
    "This is completely broken.",
    "I'm annoyed with this delay.",
    "The room was dirty.",
    "This laptop is useless.",
    "I regret going there.",
    "That was an awful experience.",
    "This is a total disaster.",
    "I'm angry about this charge.",
    "The quality is very poor.",
    "This is not worth it.",
    "I hate waiting this long.",
    "That was so unpleasant.",
    "This design looks awful.",
    "I'm tired of these errors.",
    "The staff were unhelpful.",
    "This is a rip-off.",
    "I can't believe how bad this is.",
    "That was incredibly rude.",
    "This product stopped working.",
    "I'm sick of these problems.",
    "The trip was exhausting and stressful.",
    "This is such a hassle.",
]

NEGATIVE_LONG = [
    "I hate this product because it stopped working just two days after I bought it.",
    "The service was terrible and very disappointing, and nobody seemed to care about fixing it.",
    "The food tasted awful and was served cold, which completely ruined the evening for us.",
    "The experience was frustrating and a complete waste of time from start to finish.",
    "I regret buying this item because the quality was nowhere near what was advertised online.",
    "The hotel room was dirty, the air conditioning was broken, and no one came to help.",
    "This laptop crashes constantly, loses my work, and the battery barely lasts an hour.",
    "The customer support team was rude, unhelpful, and kept transferring me between departments for no reason.",
    "I was really looking forward to this trip, but the delays and cancellations ruined everything.",
    "The movie dragged on far too long, the plot made no sense, and the ending was unsatisfying.",
    "This restaurant used to be great, but the food quality and service have gone downhill badly.",
    "The package arrived broken, the box was crushed, and half the items inside were missing.",
    "I've called three times about this billing error, and nobody has bothered to fix it yet.",
    "The instructions were confusing and incomplete, so I ended up assembling half of it wrong.",
    "This app keeps crashing every time I try to save my work, and it's incredibly frustrating.",
    "The whole event felt disorganized, the staff seemed overwhelmed, and nothing started on time.",
    "I regret choosing this company; the delivery was late, damaged, and the refund process was painful.",
    "The noise from the neighbors kept us up all night, and complaints to management went nowhere.",
    "This is the worst customer experience I have had in years, and I will not be returning.",
    "The product description was misleading, and what actually arrived looked nothing like the photos.",
]

NEUTRAL_SHORT = [
    "It is raining outside today.",
    "The meeting starts at 10 a.m.",
    "The book has 250 pages.",
    "The package arrived on Monday.",
    "The store closes at 9 p.m.",
    "The train leaves in ten minutes.",
    "She is reading a book.",
    "He is working in his office.",
    "The bus stop is around the corner.",
    "The report is due tomorrow.",
    "The temperature today is 20 degrees.",
    "The museum opens at 9 a.m.",
    "I bought the product yesterday.",
    "The car is parked outside.",
    "The meeting was rescheduled to Friday.",
    "The document has three sections.",
    "The flight departs from gate 12.",
    "The office is on the third floor.",
    "The recipe calls for two eggs.",
    "The store is located downtown.",
    "The class starts next week.",
    "The invoice was sent by email.",
    "The printer is out of paper.",
    "The library is open until 8 p.m.",
    "The weather forecast predicts clouds tomorrow.",
    "The password was reset this morning.",
    "The article was published last year.",
    "The room has two windows.",
    "The car needs an oil change.",
    "The event is scheduled for Saturday.",
    "The parking garage is next to the building.",
    "The email was sent at noon.",
    "The form has five questions.",
    "The bridge connects the two towns.",
    "The clock on the wall shows three.",
    "The parcel weighs two kilograms.",
    "The elevator stops on every floor.",
    "The lecture lasts about an hour.",
    "The road was recently repaved.",
    "The file was saved to the folder.",
]

NEUTRAL_LONG = [
    "The meeting has been moved from the main conference room to the smaller room down the hall.",
    "According to the schedule, the delivery truck is expected to arrive sometime between noon and 2 p.m.",
    "The report contains four sections covering budget, timeline, staffing, and next steps for the quarter.",
    "The train departs from platform 6 every weekday morning at 7:45 and arrives downtown by 8:20.",
    "The new policy applies to all employees who started before the beginning of this calendar year.",
    "The store is open from 9 a.m. to 9 p.m. on weekdays and closes earlier on Sundays.",
    "The document outlines the steps required to submit a request and the expected turnaround time.",
    "The building has three floors, with the reception desk located on the ground level near the entrance.",
    "The survey was sent to all participants last week and responses are due by the end of the month.",
    "The car requires an oil change every five thousand miles according to the manufacturer's manual.",
    "The conference will be held in the downtown convention center over the course of three days.",
    "The invoice lists the itemized charges along with the payment due date at the bottom of the page.",
    "The weather forecast for this week shows a mix of clouds and sun with mild temperatures throughout.",
    "The library recently updated its hours and is now open an extra hour on weekday evenings.",
    "The software update includes changes to the settings menu and a revised version number.",
    "The committee will meet on the first Tuesday of every month to review ongoing projects.",
    "The package was shipped from the warehouse on Tuesday and is expected within five business days.",
    "The form requires your name, address, and a signature at the bottom of the second page.",
    "The class covers three main topics over the course of six weekly sessions.",
    "The building's elevator is currently being serviced and is expected to reopen later this afternoon.",
]


def all_sentences():
    """Returns list of (text, label) tuples for every hand-written sentence."""
    rows = []
    rows += [(t, "positive") for t in POSITIVE_SHORT + POSITIVE_LONG]
    rows += [(t, "negative") for t in NEGATIVE_SHORT + NEGATIVE_LONG]
    rows += [(t, "neutral") for t in NEUTRAL_SHORT + NEUTRAL_LONG]
    return rows


if __name__ == "__main__":
    rows = all_sentences()
    from collections import Counter
    print(f"Total hand-written sentences: {len(rows)}")
    print(Counter(label for _, label in rows))
